# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lB1X4Ni9LzT9GR4Ys6I1Fg14i1Xc-1P0
"""

# Bankomat simulyatori
from IPython.display import clear_output
from termcolor import colored

balance = 500000  # boshlang'ich balans
password = "1234"
max_attempts = 3
attempts = 0

print(colored("🏧 Bankomatga xush kelibsiz!", "cyan"))

while attempts < max_attempts:
    user_password = input("Parolni kiriting: ")
    if user_password == password:
        print(colored("✔ Muvaffaqiyatli kirdingiz!\n", "green"))
        break
    else:
        attempts += 1
        print(colored(f"❌ Parol noto'g'ri! Qolgan urinishlar: {max_attempts - attempts}", "red"))
else:
    print(colored("🔒 Siz 3 marta noto'g'ri kirdingiz. Tizim bloklandi!", "red"))
    raise SystemExit

# Interaktiv menyu
while True:
    print("\n--- M E N U ---")
    print("1. Balansni ko'rish")
    print("2. Pul yechish")
    print("3. Pul qo'yish")
    print("4. Chiqish")

    choice = input("Tanlang (1/2/3/4): ")

    if choice == "1":
        print(colored(f"💰 Sizning balansingiz: {balance} so'm", "cyan"))

    elif choice == "2":
        try:
            amount = int(input("Yechmoqchi bo'lgan summani kiriting: "))
            if amount <= 0:
                print(colored("❌ Iltimos, musbat summa kiriting!", "red"))
            elif amount <= balance:
                balance -= amount
                print(colored(f"✔ {amount} so'm yechildi. Yangi balans: {balance} so'm", "green"))
            else:
                print(colored("❌ Balansda yetarli mablag' yo'q!", "red"))
        except ValueError:
            print(colored("❌ Iltimos, to'g'ri raqam kiriting!", "red"))

    elif choice == "3":
        try:
            amount = int(input("Kiritmoqchi bo'lgan summani kiriting: "))
            if amount <= 0:
                print(colored("❌ Iltimos, musbat summa kiriting!", "red"))
            else:
                balance += amount
                print(colored(f"✔ {amount} so'm qo'shildi. Yangi balans: {balance} so'm", "green"))
        except ValueError:
            print(colored("❌ Iltimos, to'g'ri raqam kiriting!", "red"))

    elif choice == "4":
        print(colored("👋 Tizimdan chiqdingiz. Xayr!", "cyan"))
        break

    else:
        print(colored("❌ Menudan to'g'ri raqam tanlang!", "red"))